### PR TITLE
change result to results in invoke response

### PR DESCRIPTION
**Pull request by shark8me**
Two changes done:

- request `results` instead of `result` as described in DEP-6
- The jobid is already Long, so casting to String fails. Therefore use `Long.toString` instead.

### CODE REVIEW

**Comment by AyushVerma2** [comment]
@shark8me : travis is failing, we need to fix that..

**Comment by mikera** [comment]
Where are we getting a Long from? Shouldn't JobID always be a String?

If this is reflecting a bug in a reference implementation, better to fix that than to cover it up in starfish-java

**Comment by AyushVerma2** [comment]
@shark8me : In Starfish-java implementation, jobId is a String data type, but while parsing the response from invoke service it is Long, I think we need to fix at the implementation of invoke service.
 Let discuss this in today call, and if changes required form starfish-java API, I will do.

**Comment by mikera** [comment]
I think Job ID should remain as a String. That's consistent with how IDs are usually shared, and allows greater flexibility for implementers (e.g. using hex strings or base encoding if they like).

I think it is better overall if starfish-java remains relatively strict, and throws exceptions if a job ID is not a String. Please add positive and negative tests for this etc.

**Comment by shark8me** [comment]
I'm ok with it being a String (note that it is still coerced into a String object). However, the JSON parsing returns a Long and not a String. 
My guess is that JSON guesses the type as Long. 
One way to handle it is to check the class of the returned JSON and cast based on that. 

w.r.t tests failing, there are [lots of failures](https://travis-ci.com/DEX-Company/starfish-java/builds/133798375) 
```sh
Tests run: 272, Failures: 2, Errors: 42, Skipped: 3
```

**Comment by mikera** [comment]
The parser should only return a Long if the JSON contains a number rather than a string, i.e. `{"foo":1}`. I just added a test in starfish-java to verify this - `{"foo":"1"}` gets parsed correctly as a string value of `"1"`

I think this therefore must be an error on the server side - presumably a Koi issue in this case?

**Comment by shark8me** [comment]
In that case I'll change Koi to wrap the Long as a String

**Comment by AyushVerma2** [comment]
@shark8me: this branch has conflict, seems Mike has already modified the code for the same.

**Comment by shark8me** [comment]
I've resolved the conflict

**Pull request merged**
